### ISSUE TITLE
Institution field not being correctly populated

### ISSUE THREAD

**Issue by dbranchini** [cul-it/cugir-geoblacklight#48]
Need to investigate where the breakdown is.  Institution should be Cornell for all records (at this point).  Author will contains the value for the publisher.

**Comment by hudajkhan** [comment]
Updated the XSLT so that it would look for Cornell/Mann Library in any of the matching elements and not just the first one (e.g. <xsl:when test="distinfo/distrib/cntinfo/cntorgp/cntorg[contains(text(), 'Mann Library')]">) . Keith also updated the metadata of one of the items that didn't have Cornell in the distribution info.  Cornell is now the only institution showing up in the list.
